## Python code examples
### Numpy basic

#### Numpy is a python library for array and matrices. In this note, we will cover very basics of numpy.

In [1]:
import numpy as np

x = np.array([[1, 2, 3, 4 ,5], [1, 2, 3, 4, 5]])

print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))

print(x)

x has dimensions: (2, 5)
x is an object of type: <class 'numpy.ndarray'>
[[1 2 3 4 5]
 [1 2 3 4 5]]


In [2]:
# np.arange
X = np.arange(20)
print(X)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [3]:
X = np.arange(start=10, stop=20, step=2)
print(X)

print(X[0])
print(X[4])

X[0]=3

print("After change X[0]", X)

[10 12 14 16 18]
10
18
After change X[0] [ 3 12 14 16 18]


#### You can generate a matrix using np.zeros, np.ones and np.fulls. You also can reshape 1 dim array to make a matrix

In [4]:
X = np.zeros((5, 5))
print(X, "\n")
print("Shape of X", X.shape)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

Shape of X (5, 5)


In [5]:
X= np.full((3, 3), 11)
print(X, "\n")

[[11 11 11]
 [11 11 11]
 [11 11 11]] 



In [6]:
X = np.arange(20).reshape((4,5))
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


#### Generate matrix with specific values 

In [7]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6,7], [8,9,10]])
ab = np.dot(a,b)

print(a)
print(b)
print("Matrix multiplication (Dot product):")
print(ab)

[[1 2]
 [3 4]]
[[ 5  6  7]
 [ 8  9 10]]
Matrix multiplication (Dot product):
[[21 24 27]
 [47 54 61]]


#### Can use matrix instead of array

In [8]:
a = np.matrix([[1,2], [3,4]])
b = np.matrix([[5,6,7], [8,9,10]])
ab1 = np.dot(a,b)
ab2 = a *b
print(a, "\n")
print(b,"\n")

print("Matrix multiplication using dot product:")
print(ab1, "\n")
print("Matrix multiplication using *:")
print(ab2, "\n")


[[1 2]
 [3 4]] 

[[ 5  6  7]
 [ 8  9 10]] 

Matrix multiplication using dot product:
[[21 24 27]
 [47 54 61]] 

Matrix multiplication using *:
[[21 24 27]
 [47 54 61]] 



#### Generate Diagonal matrix 

In [9]:
x1 = np.arange(1,5)
x1_diag = np.diag(x1)

print("Vector for diag")
print(x1 ,"\n")

print("Diag matrix:")
print(x1_diag)


Vector for diag
[1 2 3 4] 

Diag matrix:
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Combine arrays...

In [11]:
X = np.array([1, 2])
Y = np.array([3, 4])

np.vstack([X, Y])

array([[1, 2],
       [3, 4]])

In [12]:
np.hstack([X, Y])

array([1, 2, 3, 4])

#### Transpose 

In [13]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6,7], [8,9,10]])

print("transpose:")
print(a.T, "\n")
print(b.T, "\n")


abt1 = np.dot(a,b).T
abt2 = np.dot(b.T,a.T)

print("Show (ab)^T is the same as b^T a^T:")
print(abt1, "\n")
print(abt2, "\n")


transpose:
[[1 3]
 [2 4]] 

[[ 5  8]
 [ 6  9]
 [ 7 10]] 

Show (ab)^T is the same as b^T a^T:
[[21 47]
 [24 54]
 [27 61]] 

[[21 47]
 [24 54]
 [27 61]] 



#### Inverse 

In [15]:
a_inv = np.linalg.inv(a)

print("Inverse")
print(a_inv, "\n")
print(np.dot(a,a_inv), "\n")



Inverse
[[-2.   1. ]
 [ 1.5 -0.5]] 

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]] 

